# Site wide configuration
title: "RecordService"
description: "An abstraction layer between storage managers (for example, HDFS, HBase, Kudu) and compute frameworks (for example, MapReduce, Spark, Hive)."
logo: "/img/rs120x120.png" # 120x120 px default image used for Twitter summary card
teaser: # 400x250 px default teaser image used in image archive grid
locale: en
url:
examplesUrl: "https://github.com/cloudera/RecordServiceClient/tree/master/java/examples"
examplesSparkUrl: "http://github.com/cloudera/RecordServiceClient/tree/master/java/examples-spark"

# Jekyll configuration

sass:
    sass_dir: _sass
    style: compressed
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..3
highlighter: pygments
gems:
  - jekyll-sitemap


# Site owner
owner: 
  name: RecordService
  email: ddawson@cloudera.com
  twitter:
  google:
    ad-client:
    ad-slot:
  bio:
  avatar: bio-photo.jpg # 160x160 px image for author byline
  disqus-shortname:


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
